sudo: required
dist: trusty
notifications:
  email: false
language: node_js
node_js:
  - '8'
before_install:
  - npm install -g npm
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
jobs:
  include:
    - stage: tests
      name: Frontend tests
      cache:
        directories:
          - frontend/node_modules
      install:
        - cd frontend
        - npm install
      script:
        - npm run lint
    - stage: tests
      name: Backend tests
      cache:
        directories:
          - backend/node_modules
      before_install:
        - docker-compose up -d
      install:
        - cd backend
        - npm install
      script:
        - npm run lint
      env:
        - DB_URI=mongodb://localhost:27017
        - DB_USER=user
        - DB_PASS=pass
deploy:
  provider: script
  script: bash heroku_push
services:
 - docker